[package]
name = "psodropcheck"
version = "1.0.0"
authors = ["Jake"]

[dependencies]
time = "0.1" 
byteorder = "0.5.1"
gtk = {version = "*", features=["v3_16"]}
gdk = "*"
glib = "*"
pango = "*"
memmem = "*"